version: '3.7'
services:
  test-nginx:
    restart: always
    build:
      context: ./packages/nginx/test
      dockerfile: Dockerfile.test
    ports:
      - '8080:80'
  test-accounts-service:
    build:
      context: ./packages/accounts-service
      dockerfile: Dockerfile.test
    volumes:
      - ./packages/accounts-service:/test-accounts-service
    ports:
      - '5000:5000'
    env_file:
      - ./packages/accounts-service/test.env
    environment:
      - NODE_ENV=test
  test-environments-service:
    build:
      context: ./packages/environments-service
      dockerfile: Dockerfile.test
    volumes:
      - ./packages/environments-service:/test-environments-service
    ports:
      - '5001:5001'
    env_file:
      - ./packages/environments-service/test.env
    environment:
      - NODE_ENV=test
  test-api-gateway:
    build:
      context: ./packages/api-gateway
      dockerfile: Dockerfile.test
    volumes:
      - ./packages/api-gateway:/test-api-gateway
    ports:
      - '7000:7000'
    env_file:
      - ./packages/api-gateway/test.env
    environment:
      - NODE_ENV=test
    restart: on-failure
  test-client:
    restart: always
    build:
      context: ./packages/client
      dockerfile: Dockerfile.test
    volumes:
      - ./packages/client:/test-app
    ports:
      - '3000:3000'
    stdin_open: true
  test-redis-service:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  test-postgres-service:
    image: postgres:11.6-alpine
    restart: always
    ports:
      - '5434:5432'
    env_file:
      - ./testable-postgres.env
