version: '3.7'
services:
  dev-postgres-service:
    image: postgres:11.6-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./postgres.env
  dev-redis-service:
    image: redis
    restart: always
    ports:
      - '6379:6379'
