version: '3.7'
services:
  dev-nginx:
    restart: always
    build: ./docker/nginx/dev
    ports:
      - '8080:80'
  dev-accounts-service:
    build:
      context: .
      dockerfile: ./docker/accounts-service/Dockerfile.dev
    volumes:
      - /usr/src/app/packages/accounts-service/node_modules
      - /usr/src/app/packages/common/node_modules
      - ./packages/accounts-service:/usr/src/app/packages/packages/service
      - ./packages/common:/usr/src/app/packages/common
    ports:
      - '5000:5000'
    env_file:
      - ./packages/accounts-service/development.env
  dev-environments-service:
    build:
      context: .
      dockerfile: ./docker/environments-service/Dockerfile.dev
    volumes:
      - /usr/src/app/packages/environments-service/node_modules
      - /usr/src/app/packages/common/node_modules
      - ./packages/environments-service:/usr/src/app/packages/service
      - ./packages/common:/usr/src/app/packages/common
    ports:
      - '5001:5001'
    env_file:
      - ./packages/environments-service/development.env
  dev-api-gateway:
    build:
      context: .
      dockerfile: ./docker/api-gateway/Dockerfile.dev
    volumes:
      - /usr/src/app/packages/api-gateway/node_modules
      - /usr/src/app/packages/common/node_modules
      - ./packages/api-gateway:/usr/src/app/packages/service
      - ./packages/common:/usr/src/app/packages/common
    ports:
      - '7000:7000'
    env_file:
      - ./packages/api-gateway/development.env
    restart: on-failure
  dev-client:
    restart: always
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile.dev
    volumes:
      - /usr/src/app/packages/client/node_modules
      - /usr/src/app/packages/common/node_modules
      - ./packages/client:/usr/src/app/packages/client
      - ./packages/common:/usr/src/app/packages/common
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  dev-postgres-service:
    image: postgres:11.6-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./postgres.env
  dev-redis-service:
    image: redis
    restart: always
    ports:
      - '6379:6379'
