version: '3.7'
services:
  test-nginx:
    restart: always
    build:
      context: ./packages/nginx/test
      dockerfile: Dockerfile.test
    ports:
      - '8080:80'
  test-redis-service:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  test-postgres-service:
    image: postgres:11.6-alpine
    restart: always
    ports:
      - '5434:5432'
    env_file:
      - ./testable-postgres.env
