name: update-agm

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  push-services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run external services
        run: |
          docker-compose up -d
          echo "Waiting for PostgreSQL database to launch..."
          while ! nc -z localhost:5432; do
            sleep 0.1
          done
          echo "PostgreSQL database launched"     
          echo "Waiting for Redis instance to launch..."
          while ! nc -z localhost:6379; do
            sleep 0.1
          done
          echo "Redis instance launched"
      - name: Install dependencies
        run: |
          cd packages/accounts-service
          npm install
          cd ../environments-service
          npm install
      - name: Run services
        run: |
          cd packages/accounts-service
          npm run dev
          cd ../environments-service
          npm run dev
      - name: Push running services to AGM
        run: |
          echo "Waiting for accounts service to startup..."
          while ! nc -z localhost:5000; do
            sleep 0.1
          done
          cd packages/accounts-service
          npm run apollo-push:dev
          echo "Waiting for environments service to startup..."
          while ! nc -z localhost:5001; do
            sleep 0.1
          done
          cd ../environments-service
          npm run apollo-push:dev
